name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # roda todos os dias às 00:00 UTC
  workflow_dispatch:       # permite rodar manualmente

# garante permissão de escrita para publicar na branch 'output'
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: PadawanXXVI
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
